### ISSUE TITLE
NullPointerException being thrown for unknown reason. No subsequent queries then succeed.

### ISSUE THREAD

**Issue by MurrayFurtado** [introproventures/graphql-jpa-query#191]
Any idea why this is happening? It just suddenly starts happening.

`java.lang.NullPointerException: null
        at org.hibernate.engine.internal.StatefulPersistenceContext.clear(StatefulPersistenceContext.java:235)
        at org.hibernate.internal.SessionImpl.internalClear(SessionImpl.java:395)
        at org.hibernate.internal.SessionImpl.clear(SessionImpl.java:387)
        at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:350)
        at com.sun.proxy.$Proxy131.clear(Unknown Source)
        at com.introproventures.graphql.jpa.query.schema.impl.GraphQLJpaQueryDataFetcher.get(GraphQLJpaQueryDataFetcher.java:113)
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:261)
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:202)
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:70)
        at graphql.execution.Execution.executeOperation(Execution.java:159)
        at graphql.execution.Execution.execute(Execution.java:101)
        at graphql.GraphQL.execute(GraphQL.java:573)
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:515)
        at graphql.GraphQL.executeAsync(GraphQL.java:489)
        at graphql.GraphQL.execute(GraphQL.java:420)
        at com.introproventures.graphql.jpa.query.schema.impl.GraphQLJpaExecutor.execute(GraphQLJpaExecutor.java:72)`

**Comment by igdianov** [comment]
@MurrayFurtado The `GraphQLJpaQueryDataFetcher.get` is calling `EntityManager.clear()`  clear session persistent context to avoid getting stale objects cached in the same session between requests with different search criteria:

https://github.com/introproventures/graphql-jpa-query/blob/7ce947d72b9dc6ce0e64d35dadf0d4b21a3f5dd7/graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java#L113

This looked like a Hibernate bug to me.

Have you updated any dependencies lately?

**Comment by MurrayFurtado** [comment]
So I have updated to the latest hibernate version and this issue still persists and is unrecoverable from - ie my server needs restarting.  Can you not put some exception logic in to plug this? How else can I handle it?

The exception has a similar stacktrace:

`java.lang.NullPointerException: null
	at org.hibernate.engine.internal.StatefulPersistenceContext.clear(StatefulPersistenceContext.java:235)
	at org.hibernate.internal.SessionImpl.internalClear(SessionImpl.java:395)
	at org.hibernate.internal.SessionImpl.clear(SessionImpl.java:387)
	at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:350)
	at com.sun.proxy.$Proxy154.clear(Unknown Source)
	at com.introproventures.graphql.jpa.query.schema.impl.GraphQLJpaQueryDataFetcher.get(GraphQLJpaQueryDataFetcher.java:113)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:261)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:202)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:70)
	at graphql.execution.Execution.executeOperation(Execution.java:159)
	at graphql.execution.Execution.execute(Execution.java:101)
	at graphql.GraphQL.execute(GraphQL.java:573)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:515)
	at graphql.GraphQL.executeAsync(GraphQL.java:489)
	at graphql.GraphQL.execute(GraphQL.java:420)
	at com.introproventures.graphql.jpa.query.schema.impl.GraphQLJpaExecutor.execute(GraphQLJpaExecutor.java:72)
	at com.introproventures.graphql.jpa.query.schema.impl.GraphQLJpaExecutor$$FastClassBySpringCGLIB$$3c8ebb24.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)`
