### ISSUE TITLE
More unrecoverable errors thrown. What to do?

### ISSUE THREAD

**Issue by MurrayFurtado** [introproventures/graphql-jpa-query#199]
I have seen 2 different errors thrown by graphql-jpa-query which take down my spring boot app:

`
14:40:13.993 [https-jsse-nio-8080-exec-8] WARN  g.e.SimpleDataFetcherExceptionHandler - Exception while fetching data (/Positions) : null
java.lang.NullPointerException: null
        at org.hibernate.event.internal.AbstractLockUpgradeEventListener.upgradeLock(AbstractLockUpgradeEventListener.java:42)
        at org.hibernate.event.internal.DefaultLoadEventListener.loadFromSessionCache(DefaultLoadEventListener.java:569)
        at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:444)
        at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:222)
        at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:281)
        at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:124)
        at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:92)
        at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1257)
        at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:1140)
        at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:682)
        at org.hibernate.type.EntityType.resolve(EntityType.java:464)
        at org.hibernate.type.ManyToOneType.resolve(ManyToOneType.java:239)
        at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:172)
`

AND

`possible non-threadsafe access to the session
org.hibernate.AssertionFailure: possible non-threadsafe access to the session
        at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:127)
        at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1151)
        at org.hibernate.loader.Loader.processResultSet(Loader.java:1010)
        at org.hibernate.loader.Loader.doQuery(Loader.java:948)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:340)
        at org.hibernate.loader.Loader.doList(Loader.java:2689)
        at org.hibernate.loader.Loader.doList(Loader.java:2672)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2506)
        at org.hibernate.loader.Loader.list(Loader.java:2501)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:504)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:395)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:220)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1508)
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1537)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1505)
        at org.hibernate.query.Query.getResultList(Query.java:132)
        at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:74)
        at com.introproventures.graphql.jpa.query.schema.impl.GraphQLJpaQueryDataFetcher.get(GraphQLJpaQueryDataFetcher.java:139)
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:261)
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:202)
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:70)
        at graphql.execution.Execution.executeOperation(Execution.java:159)
        at graphql.execution.Execution.execute(Execution.java:101)
        at graphql.GraphQL.execute(GraphQL.java:573)
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:515)
        at graphql.GraphQL.executeAsync(GraphQL.java:489)
        at graphql.GraphQL.execute(GraphQL.java:420)
`

Why are these exceptions getting thrown and how can they be prevented?

**Comment by igdianov** [comment]
@MurrayFurtado The error happens inside Hibernate when it tries to initialize collections objects from SQL query. It just a wild guess, but I think you may have `hashCode` or `equals` that use collections to calculate hash. The collections proxy object may not be initialized yet, so it fails with NPE.  If it is the case, try to exclude collections from hashCode.

**Comment by MurrayFurtado** [comment]
I have checked my code and all my collections are already excluded from hashcode operations. Do you know what else could cause this?

**Comment by igdianov** [comment]
Does it happen consistently or intermittently? Can you reproduce it running a particular query for your IDE? Then, I would put a breakpoint at 

```
org.hibernate.event.internal.AbstractLockUpgradeEventListener.upgradeLock(AbstractLockUpgradeEventListener.java:42)
```

and looked around for the cause of NPE.

**Comment by igdianov** [comment]
@MurrayFurtado Please, check out https://github.com/introproventures/graphql-jpa-query/pull/228. It may explain and solve your problems
