### ISSUE TITLE
NullPointerException on @ManyToOne relationship query

### ISSUE THREAD

**Issue by chanhengseang3** [introproventures/graphql-jpa-query#260]
Having entity with `@ManyToOne` relationship:
```java
@ManyToOne
@JoinColumn(name = "product_id")
private Product product;
```
Query:
```
node{
        product{
        id
      }
        id
        amount
      }
    }
```
get Error:
```
java.lang.NullPointerException: null
	at com.introproventures.graphql.jpa.query.schema.impl.GraphQLJpaToOneDataFetcher.getDataLoader(GraphQLJpaToOneDataFetcher.java:83) ~[graphql-jpa-query-schema-0.4.4.jar:0.4.4]
	at com.introproventures.graphql.jpa.query.schema.impl.GraphQLJpaToOneDataFetcher.get(GraphQLJpaToOneDataFetcher.java:67) ~[graphql-jpa-query-schema-0.4.4.jar:0.4.4]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270) ~[graphql-java-13.0.jar:na]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:198) ~[graphql-java-13.0.jar:na]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74) ~[graphql-java-13.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:654) ~[graphql-java-13.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:438) ~[graphql-java-13.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:388) ~[graphql-java-13.0.jar:na]
```

**Comment by igdianov** [comment]
The data fetcher expects dataLoaderRegistry at https://github.com/introproventures/graphql-jpa-query/blob/c18ca55463be036847925c28704460f1a00aac95/graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaToOneDataFetcher.java#L81

Which is set for the request at https://github.com/introproventures/graphql-jpa-query/blob/c18ca55463be036847925c28704460f1a00aac95/graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaExecutorContext.java#L83

Are you modifying context by any chance?

If not, I need more information about your model and query....

**Comment by chanhengseang3** [comment]
Thanks @igdianov , i have modifying context. Let me check on that.
