### ISSUE TITLE
NPE on initialization

### ISSUE THREAD

**Issue by tomuszom** [introproventures/graphql-jpa-query#269]
@Table(name="A")
    @Entity
    public class A
            implements Serializable {
        private static final long serialVersionUID = 1L;

        @Id
        @Column(name = "a_id", nullable = false)
        private String aId;
    }

    @Table(name = "B")
    @Entity
    public class B
            implements Serializable {
        private static final long serialVersionUID = 1L;

        @EmbeddedId
        private B_ID id;

    }

    @Embeddable
    public class B_ID
            implements Serializable {
        private static final long serialVersionUID = 1L;

        @ManyToOne
        @JoinColumn(name = "a_id", referencedColumnName = "a_id")
        @NotFound(action = NotFoundAction.EXCEPTION)
        private A a;

    }

On calling GraphQLJpaSchemaBuilder.getObjectField(Attribute attribute, EntityType baseEntity) 
getting baseEntity = null (from    
    private GraphQLFieldDefinition getObjectField(Attribute<?,?> attribute) {
        return getObjectField(attribute, null);
    }
)

attribute = unknown#a(MANY_TO_ONE)

it leads to NPE 

Caused by: java.lang.NullPointerException: null
	at com.introproventures.graphql.jpa.query.schema.impl.GraphQLJpaSchemaBuilder.getObjectField(GraphQLJpaSchemaBuilder.java:908)
	at com.introproventures.graphql.jpa.query.schema.impl.GraphQLJpaSchemaBuilder.getObjectField(GraphQLJpaSchemaBuilder.java:871)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.introproventures.graphql.jpa.query.schema.impl.GraphQLJpaSchemaBuilder.getEmbeddableType(GraphQLJpaSchemaBuilder.java:809)

**Comment by igdianov** [comment]
@tomuszom Thank you bug report! I will take a look at it
